name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install deps
      run: |
        pip install black isort flake8 mypy pytest

    - name: Format check
      run: |
        black --check .
        isort --check-only .

    - name: Lint
      run: flake8

    - name: Type check
      run: mypy fl_client fl_server fl_common fl_ml_models

    - name: Run tests
      run: pytest --maxfail=1 --disable-warnings -q
